import NextAuthProvider from "@/components/next-auth-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MiniKitProvider from "@/components/minikit-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MiniKitProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </MiniKitProvider>
      </body>
    </html>
  );
}
